### ISSUE TITLE
Authentication on MQTT

### ISSUE THREAD

**Issue by brownjl** [trickeydan/hue2mqtt-python#1]
Great project that works really well after some quick tests. I'm trying to figure out how to add a user/password to the mqtt connection. Any tips on how to do this?

**Comment by brownjl** [comment]
Figured it out... Added a set_auth_credentials within the wrappers connect function. 

Great Project... Next I need to dockerise!

**Comment by trickeydan** [comment]
Thanks! I'd happily accept a patch for username / password support or a `Dockerfile` if you write one :)
